version: '3.1'

services:
  db:
    container_name: prisma-database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - ~/prisma-postgres:/var/lib/postgresql/data
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080